### PR TITLE
Add an is_empty() method for TreiberStack, add new() for Atomic<T>

### PR DESCRIPTION
**Pull request by Ticki**

### CODE REVIEW

**Comment by aturon** [comment]
Note: this is failing the CI test.

**Comment by Ticki** [comment]
Yeah, I only tested it in nightly without `nightly` feature enabled, but it should be fixed now.

**Comment by Ticki** [comment]
@aturon Yeah, it's fixed. Travis is happy.

**Comment by aturon** [comment]
Thanks!

**Pull request merged**
