### PR TITLE
Add an is_empty() method for MsQueue

### PR DESCRIPTION
**Pull request by Ticki**

### CODE REVIEW

**Comment by aturon** [comment]
Thank you!

**Comment by aturon** [comment]
It looks like this actually broke some of the tests. Investigating now.

**Comment by aturon** [comment]
I didn't look closely at the tests before merging, which was my mistake. Many of the assertions around emptiness for these tests were broken, due to not taking concurrency into account. I've pushed a fix.

**Comment by Ticki** [comment]
Oh, sorry for that. It ran fine on my box...

**Pull request merged**
